changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: ✨ 新增功能
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug 修复
      labels:
        - bug
        - fix
    - title: 🔧 优化改进
      labels:
        - optimization
        - refactor
        - performance
    - title: 📚 文档更新
      labels:
        - documentation
        - docs
    - title: ⚠️ 破坏性变更
      labels:
        - breaking-change
